# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15jElcMCpn1YLVOknbXEcsMHiRiOdO70w
"""

a=int(input())
if a==1:
  print("Январь")
elif a==2:
  print("Февраль")
elif a==3:
  print("Март")
elif a==4:
  print("Апрель")
elif a==5:
  print("Май")
elif a==6:
  print("Июнь")
elif a==7:
  print("Июль")
elif a==8:
  print("Август")
elif a==9:
  print("Сентябрь")
elif a==10:
  print("Октябрь")
elif a==11:
  print("Ноябрь")
elif a==12:
  print("Декабрь")
else:
  print("Введите число от 1 до 12")

b=int(input())
if b % 2 == 0:
  print("Четное")
else:
  print("Нечетное")

c=int(input())
if c > 40:
  print("stonks")
else:
  print("no stonks")

def is_year_leap(f):
  if f % 4 == 0: #and f % 100 == 0 and f % 400 == 0:
    return True
  else:
    return False
is_year_leap(int(input("Введите год ")))

def is_prime(n):
  if n
    return True
  else:
    return False
is_year_leap(int(input("Введите год ")))

def is_prime(n, i=2):
    if n == 1:
        return False
    if n == 2:
        return True
    if i * i > n:
        return True
    if n % i == 0:
        return False
    return is_prime(n, i + 1)
num = int(input())
result = is_prime(num)
if result:
    print(f"Число {num} является простым")
else:
    print(f"Число {num} не является простым")

a = 10
b = 3
c = [(-138 / 2) ** 1.3]
d = [abs((-69 / 28 ** 5.1) * 4)]
if a * 3.6 > b or (b in c and b in d):
    temp = a
    a = b
    b = temp

print("a =", a)
print("b =", b)